### PR TITLE
Optimize error finding prompt template

### PR DESCRIPTION
**Pull request by jalexanderII**
Great project. After running a few tests I noticed you could improve your LLM results with a more robust prompt. I used [optimusprompt.ai](https://www.optimusprompt.ai) to produce an updated version of the prompt that appears to give better results. For example, see below for a before and after that I got. Feel free to test out OptimusPrompt for future prompt building.

**Error_message:**
`
javax.servlet.ServletException: Something bad happened at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:60) Caused by: com.example.myproject.MyProjectServletException at com.example.myproject.MyServlet.doPost(MyServlet.java:169) Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [com.example.myproject.MyEntity] at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:64) Caused by: java.sql.SQLException: Violation of unique constraint MY_ENTITY_UK_1: duplicate value(s) for column(s) MY_COLUMN in statement [...] at org.hsqldb.jdbc.Util.throwError(Unknown Source)
`

**Results:**
Output using Original Prompt: `No.`
Output using Optimized Prompt: `Based on the error message, the programming language used is Java. The file that caused the error is "MyServlet.java" located at com.example.myproject package.`

### CODE REVIEW

**Comment by jalexanderII** [comment]
@xpluscal not sure how to tag you for review. But feel free to take a look if this is helpful.

**Comment by xpluscal** [comment]
Love that @jalexanderII ! Thank you for the PR, I rebased it to merge into "development" branch so that we don't trigger the workflow run ;-)

**Comment by xpluscal** [comment]
We might need to change the input so that the filename can still be determined. The script depends on the response from GPT to be the specific filepath. Do you want to give it another go and see if you can customize your commit to return the filepath directly? @jalexanderII

**Comment by jalexanderII** [comment]
I see what you mean. Yes, I will update it so that you get the full file path.

**Pull request merged**
